In [2]:
"""
This file just adds a dummy target sentence ('blabla') to pretraining frame data.

"""
import numpy as np

In [3]:
data = np.load('pretrain_key_points_5.npy')

In [4]:
ind_vid = []
count = 0
for key in data:
    ind = []
    for k in key:
        ind.append(key[k])
        ind.append('blabla')
        count += key[k].shape[0]
#         ind.append('bla bla bla bla')
    ind_vid.append(ind)
print(count)
    
ind_vid = np.array(ind_vid)

334299


In [5]:
print(ind_vid.shape)
print(ind_vid[0])

(44, 2)
[array([[-2949.92304661,  1769.25171967,   845.59396398,   541.55254938,
        -1068.13247124],
       [-2974.61584368,  1831.16806754,   860.33254266,   540.36910146,
        -1185.57884609],
       [ -288.47848394,  2119.15329914,   869.50997017,   527.20847587,
        -1208.36909069],
       ...,
       [-2691.86224579,   807.01264199,   557.83583801,  1014.63070889,
        -1119.90381992],
       [-2697.98213807,   800.14957182,   527.00340152,   994.01825185,
        -1124.6914811 ],
       [-2708.04958718,   802.36470057,   543.3654821 ,  1005.00360051,
        -1124.75893955]])
 'blabla']


In [6]:
"""
NORMALIZATION FUNCTION
x_min = lower limit
x_max = upper limit
"""
def scale(X, x_min, x_max):
    nom = (X-X.min(axis=0))*(x_max-x_min)
    denom = X.max(axis=0) - X.min(axis=0)
    denom[denom==0] = 1
    return x_min + nom/denom 

In [24]:
np.save('pretrain_sentence_frame_mapped_5.npy', ind_vid)

In [7]:
# Only run the bellow cells if you want to pretrain on normalized data
for i in range(ind_vid.shape[0]):
    ind_vid[i][0] = scale(ind_vid[i][0],0,10)

In [8]:
print(ind_vid[1][0])

[[9.08245116 9.57190859 7.3606882  2.39471474 2.93789029]
 [0.18538806 8.6268914  7.11740254 2.41725098 3.43868369]
 [0.31711825 8.59112343 7.50563423 2.37794496 2.75932135]
 ...
 [0.659277   4.45868453 5.51650798 5.68924272 1.63686612]
 [0.75631032 4.47536279 5.44316404 5.70361058 1.63636789]
 [0.68812483 4.43647985 5.54524397 5.64771864 1.63710168]]


In [37]:
np.save('pretrain_sentence_frame_mapped_5.npy', ind_vid)